var timeline_data = [
   {
      name:'communication',
      id:1,
      items:[
         {
            name:"interview",
            occurances:[
               {
                  start:"09.01.2009"
               },
               {
                  start:"01.07.2009"
               }
            ]
         },
         {
            name:"phone_interview",
            occurances:[
               {
                  start:"03.04.2009"
               },
               {
                  start:"01.10.2009"
               }
            ]
         }
      ]
   },
   {
      name:'medications',
      id:2,
      items:[
         {
            name:"ritalin",
            occurances:[
               {
                  amount:"20",
                  unit:"mg",
                  start:"01.01.2009",
                  end:"02.05.2009"
               },
               {
                  amount:"40",
                  unit:"mg",
                  start:"02.05.2009",
                  end:"04.07.2009"
               },
               {
                  amount:"80",
                  unit:"mg",
                  start:"04.07.2009",
                  end:"06.12.2009"
               }
            ]
         },
         {
            name:"seroxat",
            occurances:[
               {
                  amount:"100",
                  unit:"mg",
                  start:"03.05.2009",
                  end:"02.09.2009"
               },
               {
                  amount:"75",
                  unit:"mg",
                  start:"02.09.2009",
                  end:"06.10.2009"
               },
               {
                  amount:"25",
                  unit:"mg",
                  start:"06.10.2009",
                  end:"30.11.2009"
               },
               {
                  amount:"50",
                  unit:"mg",
                  start:"30.11.2009",
                  end:"30.12.2009"
               }
            ]
         },
         {
            name:"panodil",
            occurances:[
               {
                  amount:"110",
                  unit:"mg",
                  start:"01.01.2009",
                  end:"02.05.2009"
               },
               {
                  amount:"80",
                  unit:"mg",
                  start:"02.05.2009",
                  end:"04.07.2009"
               },
               {
                  amount:"30",
                  unit:"mg",
                  start:"04.07.2009",
                  end:"06.12.2009"
               }
            ]
         }
      ]
   },
   {
      name:'events',
      id:3,
      items:[
         {
            name:"family",
            occurances:[
               {
                  start:"01.10.2009"
               }
            ]
         }
      ]
   },
   {
      name:'scales',
      id:4,
      items:[
         {
            name:"hsq_r",
            occurances:[
               {
                  start:"03.01.2009",
                  chart:{
                     data:{
                        result:[
                           5,
                           8,
                           13
                        ],
                        average:[
                           3,
                           5,
                           8
                        ]
                     },
                     bar_labels:[
                        "inattentive",
                        "hyperactive_impulsive",
                        "total"
                     ],
                     data_labels:[
                        "Kalli Jónsson",
                        "Meðaltal 6 ára drengja"
                     ],
                     max_score:16,
                     increment:2
                  }
               },
               {
                  start:"03.04.2009",
                  chart:{
                     data:{
                        result:[
                           4,
                           6,
                           10
                        ],
                        average:[
                           3,
                           5,
                           8
                        ]
                     },
                     bar_labels:[
                        "inattentive",
                        "hyperactive_impulsive",
                        "total"
                     ],
                     data_labels:[
                        "Kalli Jónsson",
                        "Meðaltal 6 ára drengja"
                     ],
                     max_score:16,
                     increment:2
                  }
               },
               {
                  start:"03.07.2009",
                  chart:{
                     data:{
                        result:[
                           2,
                           4,
                           6
                        ],
                        average:[
                           3,
                           5,
                           8
                        ]
                     },
                     bar_labels:[
                        "inattentive",
                        "hyperactive_impulsive",
                        "total"
                     ],
                     data_labels:[
                        "Kalli Jónsson",
                        "Meðaltal 6 ára drengja"
                     ],
                     max_score:16,
                     increment:2
                  }
               }
            ]
         },
         {
             name: "d_dtods",
             occurances:[
                {
                  start:"03.06.2009",
                  chart:{
                     data:{
                        result:[
                           2,
                           4,
                           1,
                           2,
                           4,
                           4,
                           1,
                           2,
                           4,
                           2,
                        ]
                     },
                     bar_labels:[
                        "wake_up",
                        "getting_ready",
                        "go_to_shcool",
                        "classes_before_lunch",
                        "lunch",
                        "classes_after_lunch",
                        "getting_home",
                        "early_evening",
                        "late_evening",
                        "going_to_bed" 
                     ],
                     max_score:4,
                     increment:1
                  }
               },
                {
                  start:"03.08.2009",
                  chart:{
                     data:{
                        result:[
                           1,
                           3,
                           2,
                           4,
                           2,
                           3,
                           1,
                           2,
                           3,
                           1,
                        ]
                     },
                     bar_labels:[
                        "wake_up",
                        "getting_ready",
                        "go_to_shcool",
                        "classes_before_lunch",
                        "lunch",
                        "classes_after_lunch",
                        "getting_home",
                        "early_evening",
                        "late_evening",
                        "going_to_bed" 
                     ],
                     max_score:4,
                     increment:1
                  }
               }
             ]
         }
      ]
   }
]
